### ISSUE TITLE
Byl zadán neplatný algoritmus.

### ISSUE THREAD

**Issue by janbalcarik** [isdoc/dsig-demo#1]
Dobrý den,

v metodě Sign při použití signedXml.ComputeSignature(); dojde  k chybě Byl zadán neplatný algoritmus. Změnil jsem pouze certifikát a adresy k podepisovanému XML.

Děkuji

**Comment by kosek** [comment]
A bez úprav vám demo funguje?

**Comment by janbalcarik** [comment]
Děkuji za rychlou reakci, každopádně sem blb... chyba je v certifikátu respektive jeho parametrech. viz například tento odkaz: http://www.celnisprava.cz/cz/clo/e-customs/Stranky/sha-2-v-externi-domene-cs.aspx

**Comment by kosek** [comment]
Bohužel, podpora SHA-2 není v .NET Frameworku ideální, zmínka o tom, co dělat pro starší verze, je v souboru Utils.cs. Předpokládám, že problém je tedy vyřešen a "issue" uzavírám.
